### ISSUE TITLE
deaths.csv is missing the date 2020-03-13

### ISSUE THREAD

**Issue by chadj8** [coviddata/coviddata#1]
Data for March 13 is missing from the deaths.csv file. (BTW, thanks so much for putting this data together. I was struggling with where to get the U.S. daily region data from after the main site changed their format.)

**Comment by bfosten** [comment]
Thanks for catching this; it is now fixed, and the CSVs have been updated.

The issue was that the Johns Hopkins CSSE CSV for this date had a zero-width space character in the "Province/State" CSV column name, which caused an issue in the code that read it. The issue was fixed in [this commit](https://github.com/coviddata/covid-api/commit/f7c13bd46621a512e247d781dc7476d01bb3a9a8).
