### ISSUE TITLE
Data United States

### ISSUE THREAD

**Issue by neapolis79** [coviddata/coviddata#15]
Today data of United States are missing....cumulative case and death are a 0

**Comment by bfosten** [comment]
This was due to the JHU data having 0 for these values in the initial version of [this CSV](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/04-01-2020.csv). They've updated those values, and we've refetched the updated values, so the values in our repo are now up-to-date.
