### ISSUE TITLE
Montgomery, MD data from regions/cases.csv file is wrong

### ISSUE THREAD

**Issue by jaahumadap** [coviddata/coviddata#4]
The data as I downloaded it from "https://coviddata.github.io/covid-api/v1/regions/cases.csv" does not agree with the daily update data from JHU. There should be around 200 cases according to the daily update, but the file above has not been filled in for several weeks. Any thoughts?

Thanks

**Comment by bfosten** [comment]
Since this is county data, you'll want to use the Places CSVs instead of the Regions CSVs (see [Definitions](https://github.com/coviddata/covid-api#definitions)). The [places/cases.csv](https://github.com/coviddata/covid-api#placescasescsv) file has the value that you're looking for. (We're using the same place name definitions as [Mapbox](https://docs.mapbox.com/api/search/#data-types).)

The reason that the Regions CSVs have some counties in them is that some of the earlier JHU csse_covid_19_daily_reports CSVs have counties listed in the same column as states. We're working on accounting for this in our datasets.

**Comment by jaahumadap** [comment]
Thanks for the clarification... 
But the places/cases file only starts 2020.3.22? The regions/cases file has data for Montgomery County cases starting on 2020.03.06, 4 cases up to 2020.03.09 and then it drops to 0. So, I am missing all the cases between 3.09 and 3.21. Is this still a work in progress?

**Comment by bfosten** [comment]
For anyone reading this, we're discussing the above question in #6
