### ISSUE TITLE
Why does the places.csv file start on 3/22/2020?

### ISSUE THREAD

**Issue by jaahumadap** [coviddata/coviddata#6]
I assume this is because the JHU time series files have the same information up to that date?
It would be nice to have all in one place though. Just a suggestion.

Thanks, J.

**Comment by bfosten** [comment]
The Places data is pulled from the JHU daily reports CSVs' "Admin2" column, which is how they differentiate smaller political areas from states/provinces. They added this column on 3/22, which is why our Places data starts on that date.

We're looking into either parsing the JHU data to get Places data for earlier dates or starting to use a new source for Places data. If you or anyone else has any thoughts on good alternative data sources for this, please let us know.

**Comment by bfosten** [comment]
U.S. data is now being pulled from a new New York Times data source, which has more accurate historical data. The places.csv files now have historical data going back to the beginning of recorded cases.
