### ISSUE TITLE
regions/cases.csv has a decrease in NewYork for Mar 28

### ISSUE THREAD

**Issue by jaebak** [coviddata/coviddata#9]
Hi. Thanks for providing this dataset. It helps a lot.

For some reason, regions/cases.csv has decreases for several regions on Mar 28.

**Comment by gregf83** [comment]
The Mar 28 data for most states is close, however the preceding days are inflated for some, if not all, states. NY, WA and CA are all inflated.

**Comment by bfosten** [comment]
This was related to how the U.S. data is now being pulled from the [NY Times repo](https://github.com/nytimes/covid-19-data). The inflation of some values should now be fixed (fixed in 28903f79357613ce3bcbcbb04249d16c1149f30c). Because the NY Times data doesn't have data for March 28 yet, the U.S. values are currently 0 for that date.

We're working on determining how to best address this more holistically. If any of you have any thoughts on how to best handle cases in which we have data for one set of regions for the current date, but no data for another set of regions (e.g., should we use a blank value?), let me know.

**Comment by bfosten** [comment]
Because there will be a short delay between when the JHU data (the global data) is updated and when the NY Times data (U.S. data) is updated, we'll need a temporary value for the current day's U.S. data for a short period. Commit 9150e16913e416f549852b633793d06aae6ab1c0 changes the logic so that the previous day's value is used in this case.

If anyone has any thoughts of a better way to approach this, feel free to open a new issue. The problem described in this issue has been resolved, so I'll close it.
